export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
  },
  mainContent: {
    flex: 1,
    display: 'flex',
    overflowY: 'auto',
  },
  navBar: {
    backgroundColor: 'white',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    padding: '0 16px',
  },
  navContainer: {
    maxWidth: '1280px',
    margin: '0 auto',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: '64px',
  },
  navTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#2563eb',
    margin: 0,
  },
  navMenu: {
    display: 'flex',
    gap: '8px',
    listStyle: 'none',
    margin: 0,
    padding: 0,
  },
  navButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 16px',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '500',
    transition: 'all 0.3s ease',
    backgroundColor: 'transparent',
    color: '#374151',
  },
  navButtonActive: {
    backgroundColor: '#2563eb',
    color: 'white',
  },
  pageContainer: {
    flex: 1,
    overflowY: 'auto',
    maxWidth: '1280px',
    margin: '0 auto',
    width: '100%',
    padding: '16px',
  },
  card: {
    backgroundColor: 'white',
    borderRadius: '8px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    padding: '24px',
    marginBottom: '24px',
  },
  button: {
    padding: '8px 16px',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '500',
    transition: 'all 0.3s ease',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
  },
  buttonPrimary: {
    backgroundColor: '#2563eb',
    color: 'white',
  },
  buttonPrimaryHover: {
    backgroundColor: '#1d4ed8',
  },
  buttonSecondary: {
    backgroundColor: '#9ca3af',
    color: 'white',
  },
  buttonSecondaryHover: {
    backgroundColor: '#6b7280',
  },
  buttonDanger: {
    backgroundColor: '#ef4444',
    color: 'white',
  },
  buttonDangerHover: {
    backgroundColor: '#dc2626',
  },
  input: {
    width: '100%',
    padding: '8px 12px',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    fontSize: '14px',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
  },
  inputFocus: {
    outline: 'none',
    borderColor: '#2563eb',
    boxShadow: '0 0 0 3px rgba(37, 99, 235, 0.1)',
  },
  formGroup: {
    marginBottom: '16px',
  },
  label: {
    display: 'block',
    fontSize: '14px',
    fontWeight: '600',
    color: '#374151',
    marginBottom: '8px',
  },
  errorMessage: {
    backgroundColor: '#fee',
    color: '#c33',
    padding: '12px',
    borderRadius: '4px',
    borderLeft: '4px solid #c33',
    marginBottom: '16px',
    fontSize: '14px',
  },
  successMessage: {
    backgroundColor: '#efe',
    color: '#3c3',
    padding: '12px',
    borderRadius: '4px',
    borderLeft: '4px solid #3c3',
    marginBottom: '16px',
    fontSize: '14px',
  },
  warningMessage: {
    backgroundColor: '#ffe',
    color: '#cc3',
    padding: '12px',
    borderRadius: '4px',
    borderLeft: '4px solid #cc3',
    marginBottom: '16px',
    fontSize: '14px',
  },
  infoBox: {
    backgroundColor: '#eff6ff',
    borderLeft: '4px solid #2563eb',
    padding: '16px',
    borderRadius: '4px',
    fontSize: '14px',
    marginBottom: '16px',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '24px',
    marginBottom: '24px',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    margin: '16px 0',
    backgroundColor: 'white',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
  },
  tableCell: {
    padding: '12px',
    border: '1px solid #ddd',
    textAlign: 'left',
  },
  tableHeader: {
    backgroundColor: '#4CAF50',
    color: 'white',
    fontWeight: 'bold',
  },
  tableRowEven: {
    backgroundColor: '#f9f9f9',
  },
  tableRowHover: {
    backgroundColor: '#f0f0f0',
  },
}
